name: train_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.1.2
  - mlflow=2.4.1
  - ultralytics=8.0.124
  - pip:
    - wandb==0.15.4
    - torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117