name: drowsiness_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.13
  - ipython=8.14.0
  - mlflow=2.4.1
  - pip=23.1.2
  - pywin32=305
  - opencv-python=4.8.0
  - pip:
      - wandb==0.15.4
      - playsound==1.3.0
      - ultralytics==8.0.124
      - Pillow==10.0.0